### ISSUE TITLE
have you try larger codebooks?

### ISSUE THREAD

**Issue by tachikoma777** [TencentARC/VQFR#1]
Hi, great work! Looking forward to the code release!
I have a question about the codebook, in the paper 1024 codebook entries with 256 channels was used, is it designed for small storage or efficient trainning?
Have you try larger codebooks? Will the results be better?  thanks!

**Comment by guyuchao** [comment]
Hello, now the code is released, you can have a try. The codebook size of 1024 is not designed for small storage, but follow the hyperparameters of "taming transformers for high-resolution image synthesis". In our experiments, 1024 codebook is enough to encode facial details and a larger codebook may not have significant improvement.
