### ISSUE TITLE
How to obtain the metruc_weights

### ISSUE THREAD

**Issue by helloful** [TencentARC/VQFR#13]
Hi~, I would like to know how inception_FFHQ_512. PTH and alignment_Wflw_4Hg.pth are generated when calculating FID and other indicators

**Comment by guyuchao** [comment]
You can find the google drive link or tencent weiyun link on the Readme (Evaluation Part).

**Comment by helloful** [comment]
Thank you very much for your reply, I know you have open sourced the weight parameter, but what I want to know is how the weight parameter is trained

**Comment by guyuchao** [comment]
The inception_FFHQ_512. PTH is calculated from the FFHQ-512 dataset. Please check the code "[inception_stat.py](https://github.com/TencentARC/VQFR/blob/main/metric_paper/inception_stat.py)". And for landmark, the weight is provided from [facexlib](https://github.com/xinntao/facexlib).
