### ISSUE TITLE
Hi, Training issiue

### ISSUE THREAD

**Issue by SahinTiryaki** [TencentARC/VQFR#16]
Hello;
I will train using your model, but when I was reviewing your codes, I could not find the build dataset and build data loader parts. I want to know what was done in these parts. Could you help me please ? 

![image2](https://user-images.githubusercontent.com/59391291/196222906-ab1214cc-e9f0-4bd7-ae91-7cc2ab064b74.png)

![image1](https://user-images.githubusercontent.com/59391291/196223483-6c12f139-7b80-43e6-a187-610228ccdfdb.png)

**Comment by guyuchao** [comment]
in vqfr/data/__init__.py
