### ISSUE TITLE
Where can I get the trained weights of the V2 model???

### ISSUE THREAD

**Issue by dolphin0104** [TencentARC/VQFR#17]
Hellow! Thanks for your great job and implementation!

How can I get the trained weights of the v2 models ( including v2 codebook and v2 vqfr model weights)???
The provided Google Drive seems to include only v1 models.
Can you please provide trained v2 model weights?

**Comment by guyuchao** [comment]
You can find at https://github.com/TencentARC/VQFR/releases .

**Comment by dolphin0104** [comment]
Thank you for the answer:)
