### ISSUE TITLE
about vqfr2:

### ISSUE THREAD

**Issue by Yaomingshuai** [TencentARC/VQFR#19]
decoder在训练的过程中更新了吗？
<img width="894" alt="image" src="https://user-images.githubusercontent.com/73575641/203824391-4e0cd877-bfa8-4124-a344-ab5ae9e8533c.png">
为什么要将decoder的参数固定住

**Comment by guyuchao** [comment]
We fix the decoder when training restoration, because we want to keep the texture branch with the most quality. So we only update the encoder in VQFR-v2.
