### ISSUE TITLE
Results not good enough

### ISSUE THREAD

**Issue by lazy-nurd** [TencentARC/VQFR#2]
Hey Thanks for the repository, 
But the results are not really good enough for blind face restoration. GFP-Gan had similar issue of high smoothing. GPEN works much better in restoration and preserving the overall texture and looks highly realistic. I hope you guys improve on keeping the overall structure and texture, so it does not look unrealistic.
Thanks

**Comment by AMUflorianbr** [comment]
Kind of agree with @lazy-nurd. I tried to test the code on one of the faces given as an example and it seems like it doesn't achieve to give the same results. Here is the link [https://i.ibb.co/zszVpy7/Capture.png](url) for the first picture. Maybe you got a different model I don't know

**Comment by muhammad-ahmed-ghani** [comment]
Yeah I also compared it with gfpgan and GPEN and the results are much better on GPEN and then gfpgan. I also don't know how they compare the results maybe the available pretrained model is an intermediate checkpoint and it is still in training.

**Comment by guyuchao** [comment]
> Yeah I also compared it with gfpgan and GPEN and the results are much better on GPEN and then gfpgan. I also don't know how they compare the results maybe the available pretrained model is an intermediate checkpoint and it is still in training.

Hello, could you provide your compared input examples and gfpgan and gpen results. Also you can provide the command you use to inference. And I will check whether it has bugs in the demo file.

**Comment by muhammad-ahmed-ghani** [comment]
> > Yeah I also compared it with gfpgan and GPEN and the results are much better on GPEN and then gfpgan. I also don't know how they compare the results maybe the available pretrained model is an intermediate checkpoint and it is still in training.
> 
> Hello, could you provide your compared input examples and gfpgan and gpen results. Also you can provide the command you used to inference. And I will check whether it has bugs in the demo file.

<h2>Command</h2>
```bash
python demo.py -i inputs/whole_imgs -o results -v 1.0 -s 2
```
<h2>Input Image</h2>
![img](https://user-images.githubusercontent.com/63394104/182589478-f5a57e60-84d5-4504-8c4c-bf72df5b0864.jpg)

<h2>VQFR</h2>
![img](https://user-images.githubusercontent.com/63394104/182589605-24211d1c-c233-4609-a962-1cf0b1d8c811.jpg)

<h2>GPEN</h2>
![img_GPEN](https://user-images.githubusercontent.com/63394104/182589672-f5075162-56a0-4fbb-93ef-573ce5e44e88.jpg)

**Comment by guyuchao** [comment]
> Kind of agree with @lazy-nurd. I tried to test the code on one of the faces given as an example and it seems like it doesn't achieve to give the same results. Here is the link [https://i.ibb.co/zszVpy7/Capture.png](url) for the first picture. Maybe you got a different model I don't know

The provided pretrained model is the final one in paper. It seems you directly crop the teaser figure (with yellow box) and so the result is abnormal. For you to quick reimplement our results, we add the original LQ face of teaser figure into the inputs/cropped_face directory.

**Comment by guyuchao** [comment]
> Hey Thanks for the repository, But the results are not really good enough for blind face restoration. GFP-Gan had similar issue of high smoothing. GPEN works much better in restoration and preserving the overall texture and looks highly realistic. I hope you guys improve on keeping the overall structure and texture, so it does not look unrealistic. Thanks

Thanks for your comment. We provide the inference results of GPEN above (on all four validation results). Maybe you can make a comprehensive comparison between VQFR and GPEN. VQFR can generate more natural high-frequency details. Also, we will keep on making VQFR better for blind face restoration.  If there are any other questions, feel free to reopen it.
