### ISSUE TITLE
Can VQFR2 be placed in google drive too?

### ISSUE THREAD

**Issue by szopeno** [TencentARC/VQFR#21]
The google drive link only allows one to download VQFR1.3. The second link leads to a site which I can't, unfortunately, use, because I can't speak Chinese and therefore I can't understand popup windows appearing whenever I click something. Is there a possibility to put VQFR2 model in google drive too?

EDIT: nevermind, found the model elsewhere. Closing.

**Comment by guyuchao** [comment]
Yes, in model release https://github.com/TencentARC/VQFR/releases.
