### ISSUE TITLE
Hi, training issue, "No object named 'VQFRModel' found in 'model' registry".

### ISSUE THREAD

**Issue by Sid-XXD** [TencentARC/VQFR#24]
Thanks for your fantastic work.

When I tried to train VQFR, I met a KeyError: "No object named 'VQFRModel' found in 'model' registry!". I have already downloaded the pre-trained VQ codebook and modified the configuration file, but I am unsure how to fix this error. 

Additionally, I was wondering if you could provide me with the parameters for the Generator in the VQFR model. I would greatly appreciate any information or guidance you could provide on this matter.

**Comment by numanashraf** [comment]
how you have solved this issue?

**Comment by wizaaaard** [comment]
> how you have solved this issue?
I think I have solved this issue (I suppose). I guess that the author initially only developed a unique version of the VQFRModel, so the model name in the configuration file did not include v1 or v2. Later, the author developed a second version of the model and named the new model v2. The old model was named v1, but they forgot to change it back in the configuration file. You can try adding v1 or v2 to the name of the model that cannot be found in the configuration file. But this is all my guess above.
